### ISSUE TITLE
Tugas1

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3105#1]
Nama_NRP_Tugas1.pdf
deadline: 2 Oktober 2024, 23:59

**Comment by nabilamarshasafitri** [comment]
[Nabila_2C2240003_Tugas 1.pdf](https://github.com/user-attachments/files/17178300/Nabila_2C2240003_Tugas.1.pdf)

Nama : Nabila Marsha Safitri
NRP : 2C2240003
Tugas 1

**Comment by obajariyan** [comment]
[Obaja Riyan Setiawan_2C2240015_Tugas1.pdf](https://github.com/user-attachments/files/17178355/Obaja.Riyan.Setiawan_2C2240015_Tugas1.pdf)
 Obaja Riyan Setiawan
2C2240015

**Comment by anggitaaulia6** [comment]
[Anggita Aulia Margono Putri_2C2240007_Tugas 1.pdf](https://github.com/user-attachments/files/17178353/Anggita.Aulia.Margono.Putri_2C2240007_Tugas.1.pdf)

Nama : Anggita Aulia Margono Putri
NRP : 2C2240007
Tugas 1

**Comment by Nadiaaa5** [comment]
[NADIA SIMANJUNTAK_2C2240010_COMPUTATIONAL THINKING.pdf](https://github.com/user-attachments/files/17183322/NADIA.SIMANJUNTAK_2C2240010_COMPUTATIONAL.THINKING.pdf)

Nama : Nadia Simanjuntak
NRP : 2C2240010
Tugas : 1

**Comment by rhegina-rizky-sabangga** [comment]
[RHEGINA_RIZKY_SABANGGA_2C2240013_TUGAS_1.pdf](https://github.com/user-attachments/files/17189275/RHEGINA_RIZKY_SABANGGA_2C2240013_TUGAS_1.PDF.2.pdf)

NAMA : RHEGINA RIZKY SABANGGA 
NRP : 2C2240013
Tugas : 1

**Comment by Yuliantisaniah** [comment]
[Yulianti Saniah_2C2240002_Tugas 1.docx](https://github.com/user-attachments/files/17217470/Yulianti.Saniah_2C2240002_Tugas.1.docx)

Nama : Yulianti Saniah
NRP : 2C2240002
Tugas : 1

**Comment by Yuliantisaniah** [comment]
[Yulianti Saniah_2C2240002_Tugas 1.pdf](https://github.com/user-attachments/files/17217686/Yulianti.Saniah_2C2240002_Tugas.1.pdf)

Nama : Yulianti Saniah
NRP : 2C2240002
Tugas : 1

**Comment by Zahranadz8** [comment]
[zahra nadzria_2C2240011_Tugas1.docx](https://github.com/user-attachments/files/17219344/zahra.nadzria_2C2240011_Tugas1.docx)

Nama : Zahra Nadzria Shabilla
NRP : 2C2240011
Tugas :1

**Comment by stelaalfanay** [comment]
[Stela A. Alfanay_2C2240016_Tugas 1(1).pdf](https://github.com/user-attachments/files/17219377/Stela.A.Alfanay_2C2240016_Tugas.1.1.pdf)

Nama : Stela Albertina Alfanay 
NRP    : 2C2240016
Tgs     : 1

**Comment by RentriZahrasitta** [comment]
[Rentri_2C2240012_Tugas 1.pdf](https://github.com/user-attachments/files/17220203/Rentri_2C2240012_Tugas.1.pdf)
Nama : Rentri Zahrasitta Anzariyah
NRP : 2C2240012
Tugas : 1

**Comment by YudhaPrasetyaN** [comment]
[YudhaPrasetyaNugraha_2C2240017_Tugas1.pdf](https://github.com/user-attachments/files/17228131/YudhaPrasetyaNugraha_2C2240017_Tugas1.pdf)
Nama : Yudha Prasetya Nugraha
NRP : 2C2240017
Tugas : 1

**Comment by irjifariiid** [comment]
Irji Farid I._2C2240009_Tugas1.pdf
Nama : Irji Farid Ilhamsyah
NRP : 2C2240009
Tugas : 1

**Comment by irjifariiid** [comment]
[Irji Farid I._2C2240009_Tugas1.pdf](https://github.com/user-attachments/files/17228726/Irji.Farid.I._2C2240009_Tugas1.pdf)
Nama : Irji Farid Ilhamsyah
NRP : 2C2240009
Tugas : 1

**Comment by Nabilalfiansyah** [comment]
[Nabil.Alfiansyah_2C2240005_Tugas.1.pdf](https://github.com/user-attachments/files/17229301/Nabil.Alfiansyah_2C2240005_Tugas.1.pdf)
Nama : Nabil Alfiansyah
NRP : 2C225005
Tugas : 1

**Comment by semicolon-id** [comment]
Nama: Bagas Ramadhan
NRP: 2C2240006
Tugas 1
[BagasRamadhan_2C2240006_Tugas1.docx](https://github.com/user-attachments/files/17230948/BagasRamadhan_2C2240006_Tugas1.docx)

**Comment by Zahranadz8** [comment]
[Uploading ZahraNadzria_2C2240011_Tugas1.pdf…]()
Nama : Zahra Nadzria Shabilla
NRP : 2C2240011
Tugas : 1

**Comment by ZahranRazzaqWiryawan** [comment]
[Zahran Razzaq Wiryawan_2C2240001_Tugas 1.pdf](https://github.com/user-attachments/files/17232062/Zahran.Razzaq.Wiryawan_2C2240001_Tugas.1.pdf)
Nama : Zahran Razzaq Wiryawan
NRP : 2C2240001
Tugas : 1

**Comment by YudaBhirawa** [comment]
![IMG_20241003_092856_569](https://github.com/user-attachments/assets/e68db827-4d6a-4653-b2d0-11ee6e05591d)
Nama : Yuda Bhirawa
NRP : 2C2240008

**Comment by Zahranadz8** [comment]
n

Pada Rab, 2 Okt 2024 17.35, Yudha Prasetya Nugraha ***@***.***>
menulis:
