### ISSUE TITLE
Tugas2

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3105#2]
Nama_NRP_Tugas2.pdf

**Comment by Nadiaaa5** [comment]
[NADIA SIMANJUNTAK_2C2240010_TUGAS2.pdf](https://github.com/user-attachments/files/17396558/NADIA.SIMANJUNTAK_2C2240010_TUGAS2.pdf)
Nama : Nadia Simanjuntak 
NRP : 2C2240010
Tugas : 2

**Comment by rhegina-rizky-sabangga** [comment]
[RHEGINA RIZKY SABANGGA_2C2240013_TUGAS2.pdf](https://github.com/user-attachments/files/17396952/RHEGINA.RIZKY.SABANGGA_2C2240013_TUGAS2.pdf)
Nama : RHEGINA RIZKY SABANGGA 
NRP : 2C2240013

**Comment by semicolon-id** [comment]
Nama : Bagas Ramadhan
NRP : 2C2240006
Tugas 2

[BagasRamadhan_2C2240006_Tugas2.pdf](https://github.com/user-attachments/files/17397286/BagasRamadhan_2C2240006_Tugas2.pdf)

**Comment by anggitaaulia6** [comment]
[Anggita Aulia Margono Putri_2C2240007_Tugas 2.docx](https://github.com/user-attachments/files/17397843/Anggita.Aulia.Margono.Putri_2C2240007_Tugas.2.docx)

Nama : Anggita Aulia Margono Putri
NRP : 2C2240007
Tugas 2

**Comment by anggitaaulia6** [comment]
[Anggita Aulia Margono Putri_2C2240007_Tugas 2.pdf](https://github.com/user-attachments/files/17397934/Anggita.Aulia.Margono.Putri_2C2240007_Tugas.2.pdf)

Nama : Anggita Aulia Margono Putri
NRP : 2C2240007
Tugas 2

**Comment by YudaBhirawa** [comment]
[YudaBhirawa_2C2240008_Tugas2.pdf]

Nama : Yuda Bhirawa 
NRP : 2C2240008
Tugas 2

**Comment by YudaBhirawa** [comment]
[YudaBhirawa_2C2240008_Tugas2.pdf](https://github.com/user-attachments/files/17398018/YudaBhirawa_2C2240008_Tugas2.pdf)

Nama : Yuda Bhirawa 
NRP : 2C2240008
Tugas 2

**Comment by YudhaPrasetyaN** [comment]
[Yudha Prasetya Nugraha_2C2240017_tugas2.pdf](https://github.com/user-attachments/files/17399570/Yudha.Prasetya.Nugraha_2C2240017_tugas2.pdf)
Nama : Yudha Prasetya Nugraha
NRP : 2C2240017
Tugas 2

**Comment by RentriZahrasitta** [comment]
[Rentri_2C2240012_Tugas2.pdf](https://github.com/user-attachments/files/17399824/Rentri_2C2240012_Tugas2.pdf)
Nama : Rentri Zahrasitta Anzariyah
NRP : 2C2240012
Tugas : 2

**Comment by irjifariiid** [comment]
[Irji Farid - 2C224009 - Tugas2.pdf](https://github.com/user-attachments/files/17400464/Irji.Farid.-.2C224009.-.Tugas2.pdf)
Nama : Irji Farid Ilhamsyah
NRP : 2C2240009
Tugas : 2

**Comment by Yuliantisaniah** [comment]
[
[Uploading YuliantiSaniah_2C2240002_Tugas 2,3,4.docx.pdf…]()
](url)
Nama : Yulianti Saniah
NRP : 2C2240002
Tugas : 2

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()
Nama : Yulianti Saniah
NRP : 2C2240002
Tugas : 2

**Comment by Nabilalfiansyah** [comment]
[Nabil Alfiansyah_2C2240005.pdf](https://github.com/user-attachments/files/17401422/Nabil.Alfiansyah_2C2240005.pdf)
Nama : Nabil alfiansyah
NRP : 2C2240005
Tugas 2

**Comment by stelaalfanay** [comment]
[STELA A ALFANAY-NRP2C2240016-TUGAS 2.pdf](https://github.com/user-attachments/files/17402558/STELA.A.ALFANAY-NRP2C2240016-TUGAS.2.pdf)

**Comment by rhegina-rizky-sabangga** [comment]
[RHEGINA RIZKY SABANGGA_2C2240013_TUGAS 2.pdf](https://github.com/user-attachments/files/17403541/RHEGINA.RIZKY.SABANGGA_2C2240013_TUGAS.2.pdf)
Nama : RHEGINA RIZKY SABANGGA
NRP : 2C2240013
Tugas 2

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()

Nama : Yulianti Saniah
NRP : 2C2240002
Tugas : 2

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()

Nama : Yulianti Saniah
NRP : 2C224002

**Comment by Yuliantisaniah** [comment]
Nama : Yulianti Saniah
NRP :2C224002
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_2C2240002_Tugas 2.pdf…]()

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()

**Comment by ZahranRazzaqWiryawan** [comment]
[Zahran Razaq Wiryawan_2C2240001_Tugas2.pdf](https://github.com/user-attachments/files/17412555/Zahran.Razaq.Wiryawan_2C2240001_Tugas2.pdf)
Nama : Zahran Razaq Wiryawan
NRP : 2C2240001
Tugas 2

**Comment by Yuliantisaniah** [comment]
[Uploading Yulianti Saniah_ 2C2240002_Tugas 2.pdf…]()
