### ISSUE TITLE
T3- Looping

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3105#3]

**Comment by semicolon-id** [comment]
[BagasRamadhan_2C2240006_Tugas3.pdf](https://github.com/user-attachments/files/17501368/BagasRamadhan_2C2240006_Tugas3.pdf)

Nama : Bagas Ramadhan 
NRP : 2C2240006
Tugas3 : Looping

**Comment by irjifariiid** [comment]
[IRJI FARID - 2C2240009 - Tugas3.pdf](https://github.com/user-attachments/files/17501384/IRJI.FARID.-.2C2240009.-.Tugas3.pdf)
Nama : Irji Farid Ilhamsyah
NRP : 2C2240009
Tugas3 : Looping

**Comment by irjifariiid** [comment]
[IrjiFarid_2C2240009_Tugas3.pdf](https://github.com/user-attachments/files/17501411/IrjiFarid_2C2240009_Tugas3.pdf)
Nama : Irji Farid Ilhamsyah
NRP : 2C2240009
Tugas3 : Looping

**Comment by YudhaPrasetyaN** [comment]
[YudhaPrasetyaNugraha_2C2240017_tugas3.pdf](https://github.com/user-attachments/files/17501662/YudhaPrasetyaNugraha_2C2240017_tugas3.pdf)
Nama : Yudha Prasetya Nugraha
NRP : 2C2240017
Tugas3 : looping

**Comment by obajariyan** [comment]
[Obaja Riyan Setiawan_2C2240015_Tugas3.pdf](https://github.com/user-attachments/files/17501680/Obaja.Riyan.Setiawan_2C2240015_Tugas3.pdf)
Obaja Riyan Setiawan
2C2240015

**Comment by YudaBhirawa** [comment]
[YUDABHIRAWA_2C2240008_Tugas3.pdf](https://github.com/user-attachments/files/17501672/YUDABHIRAWA_2C2240008_Tugas3.pdf)
NAMA : Yuda Bhirawa
NRP : 2C2240008
Tugas3 : Looping

**Comment by ZahranRazzaqWiryawan** [comment]
[Zahran Razaq Wiryawan_2C2240001_Tugas3.pdf](https://github.com/user-attachments/files/17501888/Zahran.Razaq.Wiryawan_2C2240001_Tugas3.pdf)
Nama : Zahran Razaq Wiryawan
NRP : 2C2240001

**Comment by nabilamarshasafitri** [comment]
[Uploading NABILA MARSHA SAFITRI_2C2240003_Tugas 3.pdf…]()

Nama : NABILA MARSHA SAFITRI
NRP : 2C2240003

**Comment by Nabilalfiansyah** [comment]
[Nabil Alfiasnyah_2C2240005_Tugas3.pdf](https://github.com/user-attachments/files/17501956/Nabil.Alfiasnyah_2C2240005_Tugas3.pdf)
 Nama : Nabill alfiansyah 
NRP : 2C2240005

**Comment by nabilamarshasafitri** [comment]
[Uploading NABILA MARSHA SAFITRI_2C2240003_Tugas 3.pdf…]()

**Comment by nabilamarshasafitri** [comment]
[NABILA MARSHA SAFITRI_2C2240003_Tugas 3.pdf](https://github.com/user-attachments/files/17502011/NABILA.MARSHA.SAFITRI_2C2240003_Tugas.3.pdf)

Nama : Nabila Marsha SAFITRI
NRP : 2C2240003

**Comment by anggitaaulia6** [comment]
[Anggita Aulia MP_2C2240007_Tugas 3.pdf](https://github.com/user-attachments/files/17502020/Anggita.Aulia.MP_2C2240007_Tugas.3.pdf)

Nama : Anggita Aulia Margono Putri
NRP : 2C2240007

**Comment by Nadiaaa5** [comment]
[Nadia Simanjuntak_2C2240010_TUGAS3.pdf](https://github.com/user-attachments/files/17502024/Nadia.Simanjuntak_2C2240010_TUGAS3.pdf)
Nama : Nadia Simanjuntak
NRP : 2C2240010
Tugas 3

**Comment by Zahranadz8** [comment]
[Zahra nadzria_2C2240011_tugas3.pdf](https://github.com/user-attachments/files/17502036/Zahra.nadzria_2C2240011_tugas3.pdf)
Nama: Zahra Nadzria Shabilla
NRP: 2C2240011
Tugas 3

**Comment by Yuliantisaniah** [comment]
[yulianti_2C2240002.pdf](https://github.com/user-attachments/files/17502048/yulianti_2C2240002.pdf)

NAMA = Yulianti Saniah
NRP = 2C224002

**Comment by nabilamarshasafitri** [comment]
[Rentri_2C2240012_Tugas3.pdf](https://github.com/user-attachments/files/17502218/Rentri_2C2240012_Tugas3.pdf)

Nama : Rentri Zahrasitta Anzariyah
NRP : 2C2240012

**Comment by rhegina-rizky-sabangga** [comment]
[RHEGINA RIZKY SABANGGA_2C2240013_ TUGAS 3.pdf](https://github.com/user-attachments/files/17502457/RHEGINA.RIZKY.SABANGGA_2C2240013_.TUGAS.3.pdf)

NAMA : RHEGINA RIZKY SABANGGA
NRP :2C2240013
TUGAS 3

**Comment by rhegina-rizky-sabangga** [comment]
[Stela Albertina Alfanay_2C2240016 Tugas 3.pdf](https://github.com/user-attachments/files/17502548/Stela.Albertina.Alfanay_2C2240016.Tugas.3.pdf)

NAMA : STELA ALBERTINA ALFANAY
NRP : 2C2240016
TUGAS 3
